include required("namespace.conf")

using: 555



#using: [pacakge::compiler,
#        pacakge::languages]



release: {


    tags: {
            extra = ["patch-01"]         
            languages = ["en", "fr"]
        }

    public: {


        compiler: {
            export = "backend"
            flags =  ["gcc", "llvm"]
            default = ["gcc"]

        }
    }

    private: {}



}